<script setup lang="ts">
const { openContact } = useContactModal()
const projects = [{ title: 'Revamping Buku KIA', description: 'Improving healthcare accessibility and comprehension through human-centered research.', tags: ['FGD', 'Concept testing'], tone: 'rose', image: '/images/project-buku-kia.png' }, { title: 'Rethinking MySuperIndo App', description: "Evaluating how Indonesian families actually engage with MySuperIndo's digital ecosystem.", tags: ['Usability test', 'Heuristic'], tone: 'olive', image: '/images/project-mysuperindo.png' }, { title: "EIGER’s Reseller Ecosystem", description: 'Evaluating operational, usability, and trust challenges within EIGER’s reseller platform.', tags: ['Stakeholders', 'In-depth interview'], tone: 'slate', image: '/images/project-eiger.png' }]
</script>

<template>
  <div class="site-shell font-sans home-page"><SiteHeader /><main>
    <section id="work" class="hero site-frame"><div class="hero-copy reveal"><p class="eyebrow">UX &amp; CX Researcher</p><h1>4+ years of CX and UX<br class="desktop-only"> research in Indonesia.<br><strong>I make the human case<br class="desktop-only"> for better products.</strong></h1><div class="button-row"><NuxtLink class="button button--solid" to="/work">View case studies <span>↘</span></NuxtLink><button class="button button--outline" type="button" @click="openContact">Let's connect <span>↗</span></button></div></div><div class="hero-art reveal reveal--late"><div class="hero-collage"><img src="/images/hero-fieldwork-collage.png" alt="Research fieldwork collage" width="850" height="849"></div></div></section>
    <section id="projects" class="projects site-frame"><div class="section-heading"><p class="eyebrow">03. Selected projects</p><h2>Highlighted Case Studies</h2></div><div class="project-grid"><article v-for="project in projects" :key="project.title" class="project-item"><a href="/work" class="project-visual" :class="`project-visual--${project.tone}`" :aria-label="`View ${project.title} case study`"><img :src="project.image" :alt="`${project.title} project image`" width="683" height="683"><span class="project-arrow">↗</span></a><h3>{{ project.title }}</h3><p>{{ project.description }}</p><div class="tag-row"><span v-for="tag in project.tags" :key="tag">{{ tag }}</span></div></article></div></section>
    <section id="about" class="quote site-frame"><blockquote>“Good research does not seek confirmation. It seeks understanding, placing ourselves in the user’s shoes to create experiences that truly feel human”</blockquote><cite>— Tiara Bisrina, Senior CX Researcher</cite></section>
    <section id="contact" class="contact site-frame"><h2>Let’s discuss your next project <span>→</span></h2><button class="button button--solid" type="button" @click="openContact">Get in touch <span>↗</span></button><div class="contact-links"><a href="https://www.linkedin.com" target="_blank" rel="noreferrer">LinkedIn</a><a href="#">Resume</a><a href="mailto:tbisfir@gmail.com">Email</a></div></section>
  </main><SiteFooter /></div>
</template>
